"""jd in session state

Revision ID: 37dbf12946a0
Revises: 4451f2d9e25c
Create Date: 2025-12-31 00:38:24.878979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '37dbf12946a0'
down_revision: Union[str, Sequence[str], None] = '4451f2d9e25c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_state', sa.Column('job_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_state', 'job_description')
    # ### end Alembic commands ###
