"""cascade

Revision ID: 4328cc0b23f0
Revises: 
Create Date: 2025-12-27 21:44:55.771529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4328cc0b23f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('account_user_id_fkey'), 'account', type_='foreignkey')
    op.create_foreign_key(None, 'account', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('resume_user_id_fkey'), 'resume', type_='foreignkey')
    op.create_foreign_key(None, 'resume', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('session_user_id_fkey'), 'session', type_='foreignkey')
    op.create_foreign_key(None, 'session', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('subscription_user_id_fkey'), 'subscription', type_='foreignkey')
    op.create_foreign_key(None, 'subscription', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('verification_user_id_fkey'), 'verification', type_='foreignkey')
    op.create_foreign_key(None, 'verification', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification', type_='foreignkey')
    op.create_foreign_key(op.f('verification_user_id_fkey'), 'verification', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.create_foreign_key(op.f('subscription_user_id_fkey'), 'subscription', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.create_foreign_key(op.f('session_user_id_fkey'), 'session', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'resume', type_='foreignkey')
    op.create_foreign_key(op.f('resume_user_id_fkey'), 'resume', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.create_foreign_key(op.f('account_user_id_fkey'), 'account', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
