"""rewrites

Revision ID: 4451f2d9e25c
Revises: 
Create Date: 2025-12-28 02:23:05.179614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4451f2d9e25c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage', sa.Column('rewrites', sa.Integer(), nullable=False))
    op.drop_column('usage', 'revisions')
    op.drop_column('usage', 'generations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage', sa.Column('generations', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('usage', sa.Column('revisions', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('usage', 'rewrites')
    # ### end Alembic commands ###
