"""document name column

Revision ID: 9f561cd0a2b9
Revises: e1098b22ad31
Create Date: 2026-01-05 20:02:05.789239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9f561cd0a2b9'
down_revision: Union[str, Sequence[str], None] = 'e1098b22ad31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_state', sa.Column('generated_document_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_state', 'generated_document_name')
    # ### end Alembic commands ###
