"""more session state columns

Revision ID: e1098b22ad31
Revises: 37dbf12946a0
Create Date: 2026-01-05 17:51:40.892134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1098b22ad31'
down_revision: Union[str, Sequence[str], None] = '37dbf12946a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_state', sa.Column('template_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('session_state', sa.Column('genereated_document_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('session_state', sa.Column('generated_document_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_state', 'generated_document_data')
    op.drop_column('session_state', 'genereated_document_url')
    op.drop_column('session_state', 'template_name')
    # ### end Alembic commands ###
